"""add payment method

Revision ID: 150f1ca83a7e
Revises: 9bb3f37a044b
Create Date: 2026-06-24 11:34:39.242337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '150f1ca83a7e'
down_revision: Union[str, None] = '9bb3f37a044b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_case_management_cases_id', table_name='case_management_cases')
    except Exception:
        pass
    try:
        op.drop_table('case_management_cases')
    except Exception:
        pass
    try:
        op.add_column('invoices', sa.Column('payment_method', sa.String(length=50), nullable=True))
    except Exception as e:
        print(f"Skipping add_column payment_method: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_method')
    op.create_table('case_management_cases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('case_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_description', mysql.TEXT(), nullable=True),
    sa.Column('client_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('court_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('court_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('selected_advocate', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('next_hearing_date', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_case_management_cases_id', 'case_management_cases', ['id'], unique=False)
    # ### end Alembic commands ###
