"""add payment columns to invoices

Revision ID: 3969a03516b3
Revises: 094733d59160
Create Date: 2026-06-25 05:56:35.406672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3969a03516b3'
down_revision: Union[str, None] = '094733d59160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('advocates', 'name')
    except Exception:
        pass
    try:
        op.drop_column('advocates', 'role')
    except Exception:
        pass
    try:
        op.alter_column('documents', 'filename',
                   existing_type=mysql.VARCHAR(length=255),
                   nullable=False)
    except Exception:
        pass
    try:
        op.drop_constraint('documents_ibfk_1', 'documents', type_='foreignkey')
    except Exception:
        pass
    try:
        op.create_foreign_key(None, 'documents', 'users', ['advocate_id'], ['id'])
    except Exception:
        pass
    try:
        op.drop_column('documents', 'file_path')
    except Exception:
        pass
    try:
        op.drop_column('documents', 'client_id')
    except Exception:
        pass
    try:
        op.drop_column('documents', 'document_name')
    except Exception:
        pass
    try:
        op.drop_column('documents', 'document_type')
    except Exception:
        pass
    try:
        op.add_column('invoices', sa.Column('gpay_number', sa.String(length=50), nullable=True))
    except Exception:
        pass
    try:
        op.add_column('invoices', sa.Column('upi_id', sa.String(length=100), nullable=True))
    except Exception:
        pass
    try:
        op.alter_column('users', 'phone',
                   existing_type=mysql.VARCHAR(length=20),
                   type_=sa.String(length=50),
                   existing_nullable=True)
    except Exception:
        pass
    try:
        op.alter_column('users', 'temp_password',
                   existing_type=mysql.VARCHAR(length=255),
                   type_=sa.String(length=100),
                   existing_nullable=True)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'temp_password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('invoices', 'upi_id')
    op.drop_column('invoices', 'gpay_number')
    op.add_column('documents', sa.Column('document_type', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('documents', sa.Column('document_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('documents', sa.Column('client_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('file_path', mysql.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_ibfk_1', 'documents', 'clients', ['client_id'], ['id'])
    op.alter_column('documents', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.add_column('advocates', sa.Column('role', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('advocates', sa.Column('name', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
