"""Add Tasks tables

Revision ID: 4c2417c1ca90
Revises: cc1f3870fa5c
Create Date: 2026-07-08 10:42:49.626857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c2417c1ca90'
down_revision: Union[str, None] = 'cc1f3870fa5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advocate_task_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('advocate_tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('advocate_tasks', 'title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('advocate_task_messages', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
