"""change_documents_to_longtext

Revision ID: 579525cc1a15
Revises: 3969a03516b3
Create Date: 2026-06-26 15:53:15.638202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '579525cc1a15'
down_revision: Union[str, None] = '3969a03516b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assigned_cases', 'assigned_documents',
               existing_type=mysql.TEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # op.alter_column('cases', 'documents',
    #            existing_type=mysql.TEXT(),
    #            type_=mysql.LONGTEXT(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('cases', 'documents',
    #            existing_type=mysql.LONGTEXT(),
    #            type_=mysql.TEXT(),
    #            existing_nullable=True)
    op.alter_column('assigned_cases', 'assigned_documents',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
