"""add assigned_documents column

Revision ID: 9bb3f37a044b
Revises: b1f5231e37f9
Create Date: 2026-06-24 00:50:56.013592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9bb3f37a044b'
down_revision: Union[str, None] = 'b1f5231e37f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_case_management_cases_id', table_name='case_management_cases')
    except Exception:
        pass
    try:
        op.drop_table('case_management_cases')
    except Exception:
        pass
    try:
        op.add_column('assigned_cases', sa.Column('assigned_documents', sa.Text(), nullable=True))
    except Exception as e:
        print(f"Skipping add_column assigned_documents: {e}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_cases', 'assigned_documents')
    op.create_table('case_management_cases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('case_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_description', mysql.TEXT(), nullable=True),
    sa.Column('client_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('court_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('court_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('selected_advocate', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.Column('next_hearing_date', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_case_management_cases_id', 'case_management_cases', ['id'], unique=False)
    # ### end Alembic commands ###
