"""added new tables and fields

Revision ID: b0002943251c
Revises: 3969a03516b3
Create Date: 2026-06-29 12:52:35.354857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0002943251c'
down_revision: Union[str, None] = '3969a03516b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_notifications_id', table_name='notifications')
        op.drop_table('notifications')
    except Exception:
        pass
    
    try:
        op.add_column('case_management_cases', sa.Column('created_at', sa.DateTime(), nullable=True))
    except Exception:
        pass
        
    try:
        op.add_column('case_management_cases', sa.Column('updated_at', sa.DateTime(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_management_cases', 'updated_at')
    op.drop_column('case_management_cases', 'created_at')
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('icon', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('bg', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###
