"""add status column

Revision ID: b1f5231e37f9
Revises: e30c4a2cea3e
Create Date: 2026-06-24 00:28:49.064572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b1f5231e37f9'
down_revision: Union[str, None] = 'e30c4a2cea3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # op.drop_index('ix_case_management_cases_id', table_name='case_management_cases')
    # op.drop_table('case_management_cases')

    # op.drop_column('assigned_cases', 'role')
    # op.drop_column('assigned_cases', 'enrollment_number')
    op.alter_column('clients', 'client_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('clients', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('clients', 'email',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('clients', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('clients', 'full_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('clients', 'client_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('assigned_cases', sa.Column('enrollment_number', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('assigned_cases', sa.Column('role', mysql.VARCHAR(length=100), nullable=True))
    op.create_table('case_management_cases',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('case_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('case_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('case_description', mysql.TEXT(), nullable=True),
    sa.Column('client_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('court_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('court_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('selected_advocate', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('next_hearing_date', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('documents', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_case_management_cases_id', 'case_management_cases', ['id'], unique=False)
    # ### end Alembic commands ###
