"""Add tasks and task_messages tables

Revision ID: cc1f3870fa5c
Revises: b08c737e033f
Create Date: 2026-07-07 11:36:59.326336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cc1f3870fa5c'
down_revision: Union[str, None] = 'b08c737e033f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint('user_read_activities_ibfk_1', 'user_read_activities', type_='foreignkey')
    except Exception:
        pass
    try:
        op.drop_index('ix_user_read_activities_user_id', table_name='user_read_activities')
    except Exception:
        pass
    try:
        op.drop_table('user_read_activities')
    except Exception:
        pass
    try:
        op.alter_column('advocates', 'date_of_birth',
                   existing_type=mysql.VARCHAR(length=50),
                   type_=sa.Date(),
                   existing_nullable=True)
    except Exception:
        pass
    try:
        op.alter_column('advocates', 'years_of_experience',
                   existing_type=mysql.VARCHAR(length=20),
                   type_=sa.Integer(),
                   existing_nullable=True)
    except Exception:
        pass
    try:
        op.drop_column('advocates', 'law_firm_name')
    except Exception:
        pass
    try:
        op.drop_column('advocates', 'languages_known')
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('advocates', sa.Column('languages_known', mysql.VARCHAR(length=200), nullable=True))
    except Exception:
        pass
    try:
        op.add_column('advocates', sa.Column('law_firm_name', mysql.VARCHAR(length=100), nullable=True))
    except Exception:
        pass
    try:
        op.alter_column('advocates', 'years_of_experience',
                   existing_type=sa.Integer(),
                   type_=mysql.VARCHAR(length=20),
                   existing_nullable=True)
    except Exception:
        pass
    try:
        op.alter_column('advocates', 'date_of_birth',
                   existing_type=sa.Date(),
                   type_=mysql.VARCHAR(length=50),
                   existing_nullable=True)
    except Exception:
        pass
    try:
        op.create_table('user_read_activities',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('activity_id', mysql.VARCHAR(length=150), nullable=False),
        sa.Column('created_at', mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_read_activities_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
        )
    except Exception:
        pass
    try:
        op.create_index('ix_user_read_activities_user_id', 'user_read_activities', ['user_id'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###
