export const DISTRICT_COURTS = {
  "Alappuzha": [
    "District & Sessions Court, Alappuzha",
    "Family Court, Alappuzha",
    "MACT (Motor Accidents Claims Tribunal), Alappuzha",
    "POCSO Special Court, Alappuzha",
    "Chief Judicial Magistrate Court, Alappuzha",
    "Sub Court, Alappuzha",
    "Sub Court, Cherthala",
    "Sub Court, Mavelikkara",
    "Sub Court, Chengannur",
    "Sub Court, Kayamkulam",
    "Munsiff Court, Alappuzha",
    "Munsiff Court, Ambalapuzha",
    "Munsiff Court, Cherthala",
    "Munsiff Court, Mavelikkara",
    "Munsiff Court, Chengannur",
    "Munsiff Court, Kayamkulam",
    "Munsiff Court, Haripad",
    "Judicial First Class Magistrate Court I, Alappuzha",
    "Judicial First Class Magistrate Court II, Alappuzha",
    "Judicial First Class Magistrate Court, Cherthala",
    "Judicial First Class Magistrate Court, Kayamkulam",
    "Judicial First Class Magistrate Court, Mavelikkara",
    "Judicial First Class Magistrate Court, Chengannur",
    "Judicial First Class Magistrate Court, Haripad",
    "Judicial First Class Magistrate Court, Ramankary"
  ],
  "Ernakulam": [
    "High Court of Kerala, Ernakulam (Kochi)",
    "District & Sessions Court, Ernakulam",
    "Family Court, Ernakulam (Kochi)",
    "Family Court, Muvattupuzha",
    "MACT (Motor Accidents Claims Tribunal), Ernakulam",
    "MACT, Perumbavoor",
    "MACT, Muvattupuzha",
    "CBI Special Court, Ernakulam",
    "Vigilance & Anti-Corruption Bureau Special Court, Muvattupuzha",
    "POCSO Special Court, Ernakulam",
    "Commercial Court, Ernakulam",
    "Chief Judicial Magistrate Court, Ernakulam",
    "Sub Court, Ernakulam",
    "Sub Court, Kochi (Fort Kochi)",
    "Sub Court, Aluva",
    "Sub Court, North Paravur",
    "Sub Court, Perumbavoor",
    "Sub Court, Muvattupuzha",
    "Sub Court, Kothamangalam",
    "Munsiff Court, Ernakulam",
    "Munsiff Court, Kochi (Fort Kochi)",
    "Munsiff Court, Aluva",
    "Munsiff Court, North Paravur",
    "Munsiff Court, Perumbavoor",
    "Munsiff Court, Muvattupuzha",
    "Munsiff Court, Kothamangalam",
    "Judicial First Class Magistrate Court, Ernakulam",
    "Judicial First Class Magistrate Court, Aluva",
    "Judicial First Class Magistrate Court, North Paravur",
    "Judicial First Class Magistrate Court, Perumbavoor",
    "Judicial First Class Magistrate Court, Muvattupuzha",
    "Judicial First Class Magistrate Court, Kothamangalam",
    "Judicial First Class Magistrate Court, Kakkanad",
    "Judicial First Class Magistrate Court, Kolenchery",
    "Judicial First Class Magistrate Court, Angamaly",
    "Judicial First Class Magistrate Court, Tripunithura",
    "Judicial First Class Magistrate Court, Njarakkal"
  ],
  "Idukki": [
    "District & Sessions Court, Thodupuzha",
    "Family Court, Thodupuzha",
    "MACT, Thodupuzha",
    "POCSO Special Court, Kattappana",
    "Chief Judicial Magistrate Court, Thodupuzha",
    "Sub Court, Thodupuzha",
    "Sub Court, Kattappana",
    "Sub Court, Devikulam",
    "Munsiff Court, Thodupuzha",
    "Munsiff Court, Kattappana",
    "Munsiff Court, Devikulam",
    "Munsiff Court, Peermade",
    "Judicial First Class Magistrate Court, Thodupuzha",
    "Judicial First Class Magistrate Court, Kattappana",
    "Judicial First Class Magistrate Court, Devikulam",
    "Judicial First Class Magistrate Court, Peermade",
    "Judicial First Class Magistrate Court, Nedumkandam",
    "Judicial First Class Magistrate Court, Adimali"
  ],
  "Kannur": [
    "District & Sessions Court, Thalassery",
    "Family Court, Thalassery",
    "Family Court, Kannur",
    "MACT, Thalassery",
    "MACT, Kannur",
    "POCSO Special Court, Thalassery",
    "Chief Judicial Magistrate Court, Thalassery",
    "Sub Court, Thalassery",
    "Sub Court, Kannur",
    "Sub Court, Payyannur",
    "Sub Court, Taliparamba",
    "Munsiff Court, Kannur",
    "Munsiff Court, Payyannur",
    "Munsiff Court, Taliparamba",
    "Munsiff Court, Kuthuparamba",
    "Munsiff Court, Mattannur",
    "Judicial First Class Magistrate Court, Kannur",
    "Judicial First Class Magistrate Court, Thalassery",
    "Judicial First Class Magistrate Court, Payyannur",
    "Judicial First Class Magistrate Court, Taliparamba",
    "Judicial First Class Magistrate Court, Kuthuparamba",
    "Judicial First Class Magistrate Court, Mattannur"
  ],
  "Kasaragod": [
    "District & Sessions Court, Kasaragod",
    "Family Court, Kasaragod",
    "MACT, Kasaragod",
    "POCSO Special Court, Kasaragod",
    "Chief Judicial Magistrate Court, Kasaragod",
    "Sub Court, Kasaragod",
    "Sub Court, Kanhangad",
    "Munsiff Court, Kasaragod",
    "Munsiff Court, Hosdurg (Kanhangad)",
    "Judicial First Class Magistrate Court, Kasaragod",
    "Judicial First Class Magistrate Court, Hosdurg (Kanhangad)"
  ],
  "Kollam": [
    "District & Sessions Court, Kollam",
    "Family Court, Kollam",
    "Family Court, Kottarakkara",
    "Family Court, Chavara",
    "MACT, Kollam",
    "MACT, Punalur",
    "POCSO Special Court, Kollam",
    "Chief Judicial Magistrate Court, Kollam",
    "Sub Court, Kollam",
    "Sub Court, Kottarakkara",
    "Sub Court, Punalur",
    "Sub Court, Karunagappally",
    "Munsiff Court, Kollam",
    "Munsiff Court, Kottarakkara",
    "Munsiff Court, Punalur",
    "Munsiff Court, Karunagappally",
    "Munsiff Court, Paravur",
    "Judicial First Class Magistrate Court, Kollam",
    "Judicial First Class Magistrate Court, Kottarakkara",
    "Judicial First Class Magistrate Court, Punalur",
    "Judicial First Class Magistrate Court, Karunagappally",
    "Judicial First Class Magistrate Court, Paravur",
    "Judicial First Class Magistrate Court, Sasthamcotta",
    "Judicial First Class Magistrate Court, Chavara"
  ],
  "Kottayam": [
    "District & Sessions Court, Kottayam",
    "Family Court, Kottayam",
    "Family Court, Ettumanoor",
    "MACT, Kottayam",
    "MACT, Pala",
    "POCSO Special Court, Kottayam",
    "Chief Judicial Magistrate Court, Kottayam",
    "Sub Court, Kottayam",
    "Sub Court, Pala",
    "Sub Court, Kanjirappally",
    "Sub Court, Changanassery",
    "Sub Court, Vaikom",
    "Munsiff Court, Kottayam",
    "Munsiff Court, Pala",
    "Munsiff Court, Kanjirappally",
    "Munsiff Court, Changanassery",
    "Munsiff Court, Vaikom",
    "Judicial First Class Magistrate Court, Kottayam",
    "Judicial First Class Magistrate Court, Pala",
    "Judicial First Class Magistrate Court, Kanjirappally",
    "Judicial First Class Magistrate Court, Changanassery",
    "Judicial First Class Magistrate Court, Vaikom",
    "Judicial First Class Magistrate Court, Erattupetta"
  ],
  "Kozhikode": [
    "District & Sessions Court, Kozhikode",
    "Family Court, Kozhikode",
    "Family Court, Vatakara",
    "MACT, Kozhikode",
    "MACT, Vatakara",
    "Vigilance Special Court, Kozhikode",
    "POCSO Special Court, Kozhikode",
    "Chief Judicial Magistrate Court, Kozhikode",
    "Sub Court, Kozhikode",
    "Sub Court, Vadakara",
    "Sub Court, Koyilandy",
    "Munsiff Court, Kozhikode",
    "Munsiff Court, Vadakara",
    "Munsiff Court, Koyilandy",
    "Munsiff Court, Thamarassery",
    "Judicial First Class Magistrate Court, Kozhikode",
    "Judicial First Class Magistrate Court, Vadakara",
    "Judicial First Class Magistrate Court, Koyilandy",
    "Judicial First Class Magistrate Court, Thamarassery",
    "Judicial First Class Magistrate Court, Payyoli"
  ],
  "Malappuram": [
    "District & Sessions Court, Manjeri",
    "Family Court, Manjeri",
    "Family Court, Tirur",
    "Family Court, Malappuram",
    "MACT, Manjeri",
    "MACT, Perinthalmanna",
    "POCSO Special Court, Manjeri",
    "Chief Judicial Magistrate Court, Manjeri",
    "Sub Court, Manjeri",
    "Sub Court, Tirur",
    "Sub Court, Perinthalmanna",
    "Sub Court, Ponnani",
    "Munsiff Court, Manjeri",
    "Munsiff Court, Tirur",
    "Munsiff Court, Perinthalmanna",
    "Munsiff Court, Ponnani",
    "Munsiff Court, Parappanangadi",
    "Munsiff Court, Nilambur",
    "Judicial First Class Magistrate Court, Manjeri",
    "Judicial First Class Magistrate Court, Tirur",
    "Judicial First Class Magistrate Court, Perinthalmanna",
    "Judicial First Class Magistrate Court, Ponnani",
    "Judicial First Class Magistrate Court, Parappanangadi",
    "Judicial First Class Magistrate Court, Nilambur",
    "Judicial First Class Magistrate Court, Malappuram"
  ],
  "Palakkad": [
    "District & Sessions Court, Palakkad",
    "Family Court, Palakkad",
    "Family Court, Ottapalam",
    "MACT, Palakkad",
    "MACT, Ottapalam",
    "POCSO Special Court, Palakkad",
    "Chief Judicial Magistrate Court, Palakkad",
    "Sub Court, Palakkad",
    "Sub Court, Ottapalam",
    "Sub Court, Alathur",
    "Sub Court, Mannarkkad",
    "Munsiff Court, Palakkad",
    "Munsiff Court, Ottapalam",
    "Munsiff Court, Alathur",
    "Munsiff Court, Mannarkkad",
    "Munsiff Court, Chittur",
    "Judicial First Class Magistrate Court, Palakkad",
    "Judicial First Class Magistrate Court, Ottapalam",
    "Judicial First Class Magistrate Court, Alathur",
    "Judicial First Class Magistrate Court, Mannarkkad",
    "Judicial First Class Magistrate Court, Chittur",
    "Judicial First Class Magistrate Court, Pattambi"
  ],
  "Pathanamthitta": [
    "District & Sessions Court, Pathanamthitta",
    "Family Court, Pathanamthitta",
    "Family Court, Thiruvalla",
    "MACT, Pathanamthitta",
    "POCSO Special Court, Pathanamthitta",
    "Chief Judicial Magistrate Court, Pathanamthitta",
    "Sub Court, Pathanamthitta",
    "Sub Court, Thiruvalla",
    "Sub Court, Adoor",
    "Munsiff Court, Pathanamthitta",
    "Munsiff Court, Thiruvalla",
    "Munsiff Court, Adoor",
    "Munsiff Court, Ranni",
    "Munsiff Court, Mallappally",
    "Judicial First Class Magistrate Court, Pathanamthitta",
    "Judicial First Class Magistrate Court, Thiruvalla",
    "Judicial First Class Magistrate Court, Adoor",
    "Judicial First Class Magistrate Court, Ranni"
  ],
  "Thiruvananthapuram": [
    "High Court of Kerala (Bench / Info Centre), Thiruvananthapuram",
    "District & Sessions Court, Vanchiyoor (Thiruvananthapuram)",
    "Family Court, Thiruvananthapuram",
    "Family Court, Nedumangad",
    "Family Court, Attingal",
    "MACT, Thiruvananthapuram",
    "MACT, Attingal",
    "CBI Special Court, Thiruvananthapuram",
    "Vigilance Special Court, Thiruvananthapuram",
    "POCSO Special Court, Thiruvananthapuram",
    "Chief Judicial Magistrate Court, Thiruvananthapuram",
    "Sub Court, Thiruvananthapuram",
    "Sub Court, Neyyattinkara",
    "Sub Court, Nedumangad",
    "Sub Court, Attingal",
    "Munsiff Court, Thiruvananthapuram",
    "Munsiff Court, Neyyattinkara",
    "Munsiff Court, Nedumangad",
    "Munsiff Court, Attingal",
    "Munsiff Court, Varkala",
    "Munsiff Court, Kattakkada",
    "Judicial First Class Magistrate Court, Thiruvananthapuram",
    "Judicial First Class Magistrate Court, Neyyattinkara",
    "Judicial First Class Magistrate Court, Nedumangad",
    "Judicial First Class Magistrate Court, Attingal",
    "Judicial First Class Magistrate Court, Varkala",
    "Judicial First Class Magistrate Court, Kattakkada"
  ],
  "Thrissur": [
    "District & Sessions Court, Thrissur",
    "Family Court, Thrissur",
    "Family Court, Irinjalakuda",
    "Family Court, Chavakkad",
    "MACT, Thrissur",
    "MACT, Irinjalakuda",
    "Vigilance Special Court, Thrissur",
    "POCSO Special Court, Thrissur",
    "Chief Judicial Magistrate Court, Thrissur",
    "Sub Court, Thrissur",
    "Sub Court, Irinjalakuda",
    "Sub Court, Chavakkad",
    "Sub Court, Wadakkanchery",
    "Munsiff Court, Thrissur",
    "Munsiff Court, Irinjalakuda",
    "Munsiff Court, Chavakkad",
    "Munsiff Court, Wadakkanchery",
    "Munsiff Court, Kodungallur",
    "Judicial First Class Magistrate Court, Thrissur",
    "Judicial First Class Magistrate Court, Irinjalakuda",
    "Judicial First Class Magistrate Court, Chavakkad",
    "Judicial First Class Magistrate Court, Wadakkanchery",
    "Judicial First Class Magistrate Court, Kodungallur",
    "Judicial First Class Magistrate Court, Chalakudy"
  ],
  "Wayanad": [
    "District & Sessions Court, Kalpetta",
    "Family Court, Kalpetta",
    "MACT, Kalpetta",
    "POCSO Special Court, Kalpetta",
    "Chief Judicial Magistrate Court, Kalpetta",
    "Sub Court, Kalpetta",
    "Sub Court, Sulthan Bathery",
    "Sub Court, Mananthavady",
    "Munsiff Court, Kalpetta",
    "Munsiff Court, Sulthan Bathery",
    "Munsiff Court, Mananthavady",
    "Judicial First Class Magistrate Court, Kalpetta",
    "Judicial First Class Magistrate Court, Sulthan Bathery",
    "Judicial First Class Magistrate Court, Mananthavady"
  ],
  "National / New Delhi": [
    "Supreme Court of India, New Delhi",
    "Delhi High Court, New Delhi",
    "National Green Tribunal (NGT), Principal Bench, New Delhi",
    "Central Administrative Tribunal (CAT), Principal Bench, New Delhi"
  ]
};
